server:
  port: 8081


spring:
  datasource:
    url:   jdbc:mysql://localhost:3306/jiagou?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowMultiQueries=true
    username: root
    password: 123456

